name: Creates User Using Terraform
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  create-user:
    runs-on: ubuntu-latest
    
    steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Setup Terraform
          uses: hashicorp/setup-terraform@v3

  
        - name: aws configure
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: us-east-2

        - name: Initialize Terraform
          run: terraform init
          working-directory: terraform/pipeline1
        
        - name: Validate Terraform
          run: terraform validate
          working-directory: terraform/pipeline1
          
        - name: Apply Terraform
          run: terraform apply -auto-approve
          working-directory: terraform/pipeline1